revert: 9d02565 fr
This reverts commit 17f356d062fb60255c9bdbe7e18c61ea427b26c8.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,11 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npx lint-staged
+echo "[Husky] Checking for changes..."
+
+npm run lint || (
+    echo "ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.";
+    false;
+)
+
+echo "[Husky] Everything is good!"
